---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-share

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      priorityClassName: low-priority
      nodeSelector:
        node-role: devops
      containers:
      - name: opensearch
        image: opensearchproject/opensearch:2.12.0
        ports:
        - containerPort: 9200  # OpenSearch REST API
        - containerPort: 9300  # Node communication and transport
        - containerPort: 9600  # Metrics port - Performance Analyzer
        env:
        - name: discovery.type
          value: "single-node"
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "QwerAsdfZxcv#234221"
        - name: OPENSEARCH_SECURITY_ENABLED
          value: "true"
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
          requests:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: opensearch-storage
      volumes:
      - name: opensearch-storage
        persistentVolumeClaim:
          claimName: opensearch-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
spec:
  selector:
    app: opensearch
  ports:
  - name: rest-api
    protocol: TCP
    port: 9200
    targetPort: 9200
    nodePort: 30092  # OpenSearch API exposed on NodePort    
  - name: communication
    protocol: TCP
    port: 9300
    targetPort: 9300
  - name: metrics
    protocol: TCP
    port: 9600
    targetPort: 9600
  type: NodePort  # OpenSearch api expose for jenkins
#  type: ClusterIP  # OpenSearch stays internal


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch-dashboards
  labels:
    app: opensearch-dashboards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch-dashboards
  template:
    metadata:
      labels:
        app: opensearch-dashboards
    spec:
      priorityClassName: low-priority
      nodeSelector:
        node-role: devops
      containers:
      - name: opensearch-dashboards
        image: opensearchproject/opensearch-dashboards:2.12.0
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 5601
        env:
        - name: OPENSEARCH_HOSTS
          value: "[\"https://opensearch:9200\"]"

---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboards
spec:
  selector:
    app: opensearch-dashboards
  ports:
  - name: http
    protocol: TCP
    port: 5601
    targetPort: 5601
    nodePort: 30061  # Expose on this NodePort
  type: NodePort


