apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
  type: NodePort 
  ports:
    - name: 8081-tcp
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: 8082-tcp
      protocol: TCP
      port: 8082
      targetPort: 8082
    - name: 8083-tcp
      protocol: TCP
      port: 8083
      targetPort: 8083
