apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-pvc
  namespace: devops
spec:
  storageClassName: nfs-share 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
