# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: gitea
#   namespace: devops
# spec:
#   project: default
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: devops
#   sources:
#     - repoURL: https://dl.gitea.com/charts/
#       chart: gitea-charts/gitea
#       targetRevision: 11.0.1
#       helm:
#         parameters:
#           - name: image.registry
#             value: 'dockerhub.com'
#           - name: image.repository
#             value: 'gitea/gitea'
#           - name: image.pullPolicy
#             value: 'IfNotPresent'
#           - name: nodeSelector.node-role
#             value: 'devops'
#           - name: gitea.username
#             value: 'gitea_admin'
#           - name: gitea.password
#             value: 'gitea_admin@1234'
#           - name: service.http.type
#             value: 'NodePort'
#           - name: service.http.nodePort
#             value: '30150'

#           # - name: persistence.storageClass
#           #   value: 'nfs-share'


#           # - name: ingress.enabled
#           #   value: 'false'
#           # - name: ingress.hosts
#           #   value: 'devops-gitea.doamain.com'


#     #     valueFiles:
#     #       - $values/influxdb/values-influxdb.yaml
#     # - repoURL: 'https://github.com/devops/kubernetes-config.git'
#     #   targetRevision: main
#     #   ref: values
