kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-devops-pvc
  namespace: devops
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
