kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-devops-pvc
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
