# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# -- Override the resource name prefix
# @default -- `Chart.Name`
nameOverride: "devops-jenkins"

controller:

  # -- Resource allocation (Requests and Limits)
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  # -- Set Jenkins URL if you are not using the ingress definitions provided by the chart
  jenkinsUrl:
  # -- Email address for the administrator of the Jenkins instance
  jenkinsAdminEmail: "devops@domain.com"
  
  # -- k8s node port. Only used if serviceType is NodePort
  nodePort: 31000

