controller:
  JCasC:
    configScripts:
      custom-casc-credentials: |
      
        credentials:
          system:
            domainCredentials:
            - credentials:
              - usernamePassword:
                  description: "Nexus"
                  id: "Nexus-User"
                  password: "{Nexus-password}"
                  scope: GLOBAL
                  username: "devops"
                  usernameSecret: true
              - usernamePassword:
                  description: "ansible-login-devopsuser"
                  id: "ansible-login-devopsuser"
                  password: "{ansible-password}"
                  scope: GLOBAL
                  username: "devops"
                  usernameSecret: true
              - usernamePassword:
                  description: "devops user"
                  id: "devops"
                  password: "{devops_password}"
                  scope: GLOBAL
                  username: "devops"

              - usernamePassword:
                  description: "devops-email"
                  id: "devops-email"
                  password: "{devops_password}"
                  scope: GLOBAL
                  username: "devops@domain.com"
