# Default values for jenkins plugins
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

controller:

  # If set to false, Jenkins will download the minimum required version of all dependencies.
  # -- Download the minimum required version or latest version of all dependencies
  installLatestPlugins: true

  # -- Set to true to download the latest version of any plugin that is requested to have the latest version
  installLatestSpecifiedPlugins: false

  # Without this; whenever the controller gets restarted (Evicted, etc.) it will fetch plugin updates that have the potential to cause breakage.
  # Note that for this to work, `persistence.enabled` needs to be set to `true`
  # -- Initialize only on first installation. Ensures plugins do not get updated inadvertently. Requires `persistence.enabled` to be set to `true`
  initializeOnce: false

  # Enable to always override the installed plugins with the values of 'controller.installPlugins' on upgrade or redeployment.
  # -- Overwrite installed plugins on start
  overwritePlugins: true

  # Configures if plugins bundled with `controller.image` should be overwritten with the values of 'controller.installPlugins' on upgrade or redeployment.
  # -- Overwrite plugins that are already installed in the controller image
  overwritePluginsFromImage: true

  # Plugins will be installed during Jenkins controller start
  # -- List of Jenkins plugins to install. If you don't want to install plugins, set it to `false`
  # installPlugins:
  #   - kubernetes:4314.v5b_846cf499eb_
  #   - workflow-aggregator:600.vb_57cdd26fdd7    #Pipeline
  #   - git:5.7.0
  #   - configuration-as-code:1932.v75cb_b_f1b_698d


  # -- List of plugins to install in addition to those listed in controller.installPlugins
  additionalPlugins:
    - active-directory:2.40
    - additional-metrics:146.v88cfe819665c
    - adoptopenjdk:146.v1898676a_f04e    #Eclipse Temurin installer
    - allure-jenkins-plugin:2.32.0
    - ansible:588.v2a_a_a_f345e34f
    - ansicolor:1.0.6
    - ant:518.v8d8dc7945eca_
    - antisamy-markup-formatter:173.v680e3a_b_69ff3
    - apache-httpcomponents-client-4-api:4.5.14-269.vfa_2321039a_83
    - apache-httpcomponents-client-5-api:5.5-157.vb_43ef2f6845e
    - asm-api:9.8-163.vb_2a_96d3f9c3c
    - authentication-tokens:1.144.v5ff4a_5ec5c33
    - basic-branch-build-strategies:275.vde2351b_4a_58b_
    - bootstrap5-api:5.3.7-2
    - bouncycastle-api:2.30.1.81-264.v95c79c0e772c
    - branch-api:2.1240.vca_710512d944
    - build-monitor-plugin:1.14-985.v7b_f37b_3d0b_f5
    - build-name-setter:2.5.1
    - built-on-column:1.5
    - build-timeout:1.38
    - caffeine-api:3.2.2-178.v353b_8428ed56
    - changes-since-last-success:0.6
    - checks-api:373.vfe7645102093
    - cloudbees-disk-usage-simple:241.v0ea_d9a_a_96ee8
    - cloudbees-folder:6.1037.v4cb_8573b_72a_a_
    - command-launcher:123.v37cfdc92ef67
    - commons-collections4-api:4.5.0-8.va_d5448ef9011
    - commons-compress-api:1.28.0-1
    - commons-httpclient3-api:3.1-3
    - commons-lang3-api:3.18.0-98.v3a_674c06072d
    - commons-text-api:1.14.0-194.v804a_dc3a_1b_d8
    - conditional-buildstep:1.5.0
    - config-file-provider:994.v3d4a_5fa_f353a_
    - confluence-publisher:2.0.5
    - copyartifact:770.va_6c69e063442
    - countjobs-viewstabbar:1.0.1
    - credentials-binding:702.vfe613e537e88
    - credentials:1419.v2337d1ceceef
    - cucumber-reports:5.9.0
    - dashboard-view:2.537.v5132851f6ca_f
    - deployit-plugin:24.3.0                        #XebiaLabs XL Deploy
    - display-url-api:2.217.va_6b_de84cc74b_
    - docker-commons:457.v0f62a_94f11a_3
    - docker-workflow:621.va_73f881d9232            #Docker Pipeline
    - durable-task:595.ve87b_f1318d67
    - echarts-api:6.0.0-1
    - eddsa-api:0.3.0.1-19.vc432d923e5ee
    - email-ext:1925.v1598902b_58dd
    - file-operations:353.vf3b_9b_a_f1f7f7
    - font-awesome-api:7.0.0-1
    - git-client:6.3.0
    - gitlab-api:5.6.0-100.v83f8f4b_f1129
    - gitlab-branch-source:723.v090f23d3cc49
    - gitlab-merge-request-jenkins:2.0.0
    - gitlab-plugin:1.9.8
    - gradle:2.15
    - groovy:497.v7b_061a_a_de65d
    - gson-api:2.13.1-153.vb_3d0c48a_a_b_4a_
    - handy-uri-templates-2-api:2.1.8-36.v85e4cb_234a_13    
    - hp-application-automation-tools-plugin:25.3   #OpenText Application Automation Tools
    - htmlpublisher:427
    - http_request:1.20
    - influxdb:5.0
    - instance-identity:203.v15e81a_1b_7a_38
    - ionicons-api:94.vcc3065403257
    - jackson2-api:2.19.2-408.v18248a_324cfe
    - jakarta-activation-api:2.1.3-2
    - jakarta-mail-api:2.1.3-2
    - javadoc:354.vee1a_660b_4990
    - javax-activation-api:1.2.0-8
    - javax-mail-api:1.6.2-11
    - jaxb:2.3.9-133.vb_ec76a_73f706
    - jdk-tool:83.v417146707a_3d    #Oracle Java SE Development Kit Installer
    - jersey2-api:2.47-165.ve7809a_3e87e0
    - jira-steps:2.0.180.vccfe35b_5910d
    - job-dsl:1.93
    - jobConfigHistory:1352.va_201a_8389340
    - joda-time-api:2.14.0-149.v1c3ce991d1b_9
    - jquery:1.12.4-3
    - jquery3-api:3.7.1-583.vda_6ca_102270d
    - jsch:0.2.16-95.v3eecb_55fa_b_78
    - json-api:20250517-163.v1c5da_e99c775
    - json-path-api:2.9.0-178.vca_b_c71881321
    - jsoup:1.21.1-58.vfc578e6e2610
    - junit:1335.v6b_a_a_e18534e1
    - kubernetes-client-api:7.3.1-256.v788a_0b_787114
    - kubernetes-credentials:206.vde31a_b_0f71a_c
    - log-parser:2.5.0
    - mailer:515.vd788654779b_1
    - matrix-auth:3.2.7
    - matrix-project:856.v4c352b_3a_b_23e
    - maven-plugin:3.27
    - metrics:4.2.32-481.v75f035fdc894
    - micro-focus-performance-center-integration:1.1.9        #OpenText Enterprise Performance Engineering integration With Git
    - mina-sshd-api-common:2.15.0-161.vb_200831a_c15b_
    - mina-sshd-api-core:2.15.0-161.vb_200831a_c15b_
    - msbuild:1.37
    - multibranch-build-strategy-extension:64.v348e3c69f1f5  #Pipeline: Multibranch build strategy extension
    - nexus-artifact-uploader:2.14
    - nodejs:1.6.5
    - okhttp-api:4.11.0-189.v976fa_d3379d6
    - oss-symbols-api:392.v27a_482d90083
    - parameterized-scheduler:285.ve611986d4c48
    - pipeline-build-step:571.v08a_fffd4b_0ce
    - pipeline-graph-analysis:241.vc3d48fb_b_2582
    - pipeline-graph-view:619.v92f3fcdc39db_
    - pipeline-groovy-lib:752.vdddedf804e72
    - pipeline-input-step:534.v352f0a_e98918
    - pipeline-maven-api:1563.v2e75645a_7d43
    - pipeline-maven:1563.v2e75645a_7d43                  #Pipeline Maven Integration
    - pipeline-milestone-step:138.v78ca_76831a_43
    - pipeline-model-api:2.2265.v140e610fe9d5
    - pipeline-model-definition:2.2265.v140e610fe9d5     #Pipeline: Declarative
    - pipeline-model-extensions:2.2265.v140e610fe9d5     #Pipeline: Declarative Extension Points API
    - pipeline-rest-api:2.38
    - pipeline-stage-step:322.vecffa_99f371c
    - pipeline-stage-tags-metadata:2.2265.v140e610fe9d5
    - pipeline-stage-view:2.38                             #Pipeline: Stage View
    - pipeline-utility-steps:2.19.0
    - plain-credentials:199.v9f8e1f741799
    - plugin-util-api:6.1.0                                #Plugin Utilities API
    - powershell:2.3
    - prism-api:1.30.0-1    
    - prometheus:819.v50953a_c560dd
    - qmetry-for-jira-test-management:1.12
    - rebuild:338.va_0a_b_50e29397
    - remote-file:1.24
    - role-strategy:799.v5b_e7b_ecc231e                    #Role-based Authorization Strategy
    - run-condition:243.v3c3f94e46a_8b_
    - scm-api:707.v749f968369d4
    - script-security:1378.vf25626395f49
    - snakeyaml-api:2.3-125.v4d77857a_b_402
    - sonar:2.18                                          #SonarQube Scanner
    - ssh-credentials:361.vb_f6760818e8c
    - ssh-slaves:3.1071.v0d059c7b_c555                    #SSH Build Agents
    - sshd:3.374.v19b_d59ce6610                           #SSH server
    - structs:353.v261ea_40a_80fb_
    - timestamper:1.30
    - token-macro:477.vd4f0dc3cb_cf1
    - trilead-api:2.209.v0e69b_c43c245
    - validating-string-parameter:255.v31e2e6d0d273
    - variant:70.va_d9f17f859e0
    - workflow-api:1384.vdc05a_48f535f                    #Pipeline: API
    - workflow-basic-steps:1079.vce64b_a_929c5a_          #Pipeline: Basic Steps
    - workflow-cps:4183.v94b_6fd39da_c1                   #Pipeline: Groovy
    - workflow-durable-task-step:1452.v0ee719c104a_7      #Pipeline: Nodes and Processes
    - workflow-job:1540.v295eccc9778f                     #Pipeline: Job
    - workflow-multibranch:811.vcd33d074c2a_0             #Pipeline: Multibranch
    - workflow-scm-step:437.v05a_f66b_e5ef8               #Pipeline: SCM Step
    - workflow-step-api:706.v518c5dcb_24c0                #Pipeline: Step API
    - workflow-support:976.vb_d9493c2eb_09                #Pipeline: Supporting APIs
    - xray-connector:2.6.1
