controller:

  # Below is the implementation of Jenkins Configuration as Code. Add a key under configScripts for each configuration area,
  # where each corresponds to a plugin or section of the UI. Each key (prior to | character) is just a label, and can be any value.
  # Keys are only used to give the section a meaningful name. The only restriction is they may only contain RFC 1123 \ DNS label
  # characters: lowercase letters, numbers, and hyphens. The keys become the name of a configuration yaml file on the controller in
  # /var/jenkins_home/casc_configs (by default) and will be processed by the Configuration as Code Plugin. The lines after each |
  # become the content of the configuration yaml file. The first line after this is a JCasC root element, e.g., jenkins, credentials,
  # etc. Best reference is https://<jenkins_url>/configuration-as-code/reference. The example below creates a welcome message:
  JCasC:
    configScripts:
      custom-casc-tools: |

          tool:
            ansible:
              installations:
              - home: "/usr/bin/"
                name: "ansible-79"
                properties:
                - installSource:
                    installers:
                    - command:
                        command: |-
                          sudo apt update
                          sudo apt install software-properties-common
                          sudo add-apt-repository --yes --update ppa:ansible/ansible
                          sudo apt install ansible
                        toolHome: "/usr/bin/"
            ant:
              installations:
              - name: "ant-1.10.7"
                properties:
                - installSource:
                    installers:
                    - antFromApache:
                        id: "1.10.7"

            git:
              installations:
              - home: "git"
                name: "Default"
            gradle:
              installations:
              - name: "gradle-40"
                properties:
                - installSource:
                    installers:
                    - gradleInstaller:
                        id: "4.0"
              - name: "gradle-7.5"
                properties:
                - installSource:
                    installers:
                    - gradleInstaller:
                        id: "7.5"

            groovy:
              installations:
              - name: "groovy-3.0.8"
                properties:
                - installSource:
                    installers:
                    - groovyInstaller:
                        id: "3.0.8"

              - name: "Groovy-3"
                properties:
                - installSource:
                    installers:
                    - groovyInstaller:
                        id: "3.0.8"


            jdk:
              installations:
              - name: "OpenJDK1.8.432"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk8u432-b06"

              - name: "OpenJDK11.0.2"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-11.0.20+8"

              - name: "OpenJDK11017"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-11.0.17+8"

              - name: "OpenJDK17.0.9"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-17.0.9+9"

              - name: "OpenJDK17011"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-17.0.11+9"

              - name: "OpenJDK18"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-18.0.2.1+1"

              - name: "OpenJDK21"
                properties:
                - installSource:
                    installers:
                    - adoptOpenJdkInstaller:
                        id: "jdk-21+35"


              - home: "C:\\Program Files\\Java\\jdk1.8.0_65"
                name: "Oracle-JDK-1.8"


            maven:
              installations:
              - name: "maven-3.9.8"
                properties:
                - installSource:
                    installers:
                    - maven:
                        id: "3.9.8"

              - name: "maven-3.6.3"
                properties:
                - installSource:
                    installers:
                    - maven:
                        id: "3.6.3"

            mavenGlobalConfig:
              globalSettingsProvider: "standard"
              settingsProvider: "standard"

            msBuildSQRunnerInstallation:
              installations:
              - name: "SonarScanner-Framework-V4.8"
                properties:
                - installSource:
                    installers:
                    - msBuildSonarQubeRunnerInstaller:
                        id: "5.14.0.78575"

              - name: "SonarScanner-Core-V4.8"
                properties:
                - installSource:
                    installers:
                    - msBuildSonarQubeRunnerInstaller:
                        id: "5.14.0.78575"



            msbuild:
              installations:
              - home: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\\
                  MSBuild\\Current\\Bin\\MSBuild.exe"
                name: "msbuild-VS-2019-Win103"
              - home: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\\
                  MSBuild\\Current\\Bin\\MSBuild.exe"
                name: "msbuild-VS-2019-BuildTool"
              - home: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\MSBuild\\\
                  Current\\Bin\\amd64\\MSBuild.exe"
                name: "msbuild-VS-2022-BuildTool"


            nodejs:
              installations:
              - name: "nodejs-v10.18.1"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "10.18.1"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-12.18.0"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "12.18.0"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-13.6.0"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "13.6.0"
                        npmPackages: "newman"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-v14.15.4"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "14.15.4"
                        npmPackages: "newman"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-v16.17.0"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "16.17.0"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-v18.13.0"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "18.13.0"
                        npmPackagesRefreshHours: 72

              - name: "nodejs-20.1.0"
                properties:
                - installSource:
                    installers:
                    - nodeJSInstaller:
                        id: "20.1.0"
                        npmPackagesRefreshHours: 72

            pipelineMaven:
              triggerDownstreamUponResultAborted: false
              triggerDownstreamUponResultFailure: false
              triggerDownstreamUponResultNotBuilt: false
              triggerDownstreamUponResultSuccess: true
              triggerDownstreamUponResultUnstable: false
            powerShellInstallation:
              installations:
              - home: "powershell.exe"
                name: "DefaultWindows"
              - home: "pwsh"
                name: "DefaultLinux"
            sonarRunnerInstallation:
              installations:
              - name: "Sonar-4.2"
                properties:
                - installSource:
                    installers:
                    - sonarRunnerInstaller:
                        id: "4.2.0.1873"
              - name: "Sonar-4.6"
                properties:
                - installSource:
                    installers:
                    - sonarRunnerInstaller:
                        id: "4.6.2.2472"


            # xvfb:
            #   installations:
            #   - home: "/usr/bin"
            #     name: "xvfb"


    # - name: "ant-1.10.7"
    #   properties:
    #   - installSource:
    #       installers:
    #       - antFromApache:
    #           id: "1.10.7"