apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwi-db-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiwi-uploads-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-tcms
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiwi-tcms
  template:
    metadata:
      labels:
        app: kiwi-tcms
    spec:
      priorityClassName: low-priority
      nodeSelector:
        node-role: devops
      containers:
        - name: db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: kiwi
            - name: POSTGRES_USER
              value: kiwi
            - name: POSTGRES_PASSWORD
              value: kiwi
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
        - name: web
          image: kiwitcms/kiwi:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: KIWI_DB_HOST
              value: kiwi-db
            - name: KIWI_DB_PORT
              value: "5432"
            - name: KIWI_DB_NAME
              value: kiwi
            - name: KIWI_DB_USER
              value: kiwi
            - name: KIWI_DB_PASSWORD
              value: kiwi
          volumeMounts:
            - name: uploads-storage
              mountPath: /Kiwi/uploads
            - name: settings-dir
              mountPath: /venv/lib64/python3.9/site-packages/tcms_settings_dir/email_config.py
              subPath: email_config.py
            - name: settings-dir
              mountPath: /venv/lib64/python3.9/site-packages/tcms_settings_dir/multi_tenant.py
              subPath: multi_tenant.py
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: kiwi-db-pvc
        - name: uploads-storage
          persistentVolumeClaim:
            claimName: kiwi-uploads-pvc
        - name: settings-dir
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kiwi-db
  namespace: devops
spec:
  selector:
    app: kiwi-tcms
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: kiwi-tcms
  namespace: devops
spec:
  selector:
    app: kiwi-tcms
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8443
      nodePort: 30443
  type: NodePort
