---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: devops
data:
  telegraf.conf: |
    # Telegraf Configuration
    [agent]
      interval = "50s"
    [[outputs.influxdb_v2]]
      urls = ["http://influxdb.devops.svc.cluster.local:8086"]
      token = "sfdsdsfdsfdsfds"
      
      organization = "devops"
      bucket = "devops"

    [[inputs.jenkins]]
      url = "http://myjenkins.devops.svc.cluster.local:8080"
      username = "devops"
      password = "devops"
      response_timeout = "50s"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      priorityClassName: low-priority
      nodeSelector:
        node-role: devops
      containers:
        - name: telegraf
          image: telegraf:latest
          envFrom:
            - configMapRef:
                name: telegraf-config
          volumeMounts:
            - name: telegraf-config-volume
              mountPath: /etc/telegraf/
      volumes:
        - name: telegraf-config-volume
          configMap:
            name: telegraf-config
            items:
              - key: telegraf.conf
                path: telegraf.conf


